## traefik.yml
entryPoints:
  web:
    address: ":80"

# File based configuration
providers:
  file:
    filename: "/etc/traefik/static-configuration.yml"

# Docker configuration backend
# providers:
#   docker:
#     defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: true